# Generated by Django 3.2.9 on 2021-12-13 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='科目名')),
                ('follow_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.subject')),
            ],
        ),
    ]
