# Generated by Django 3.2.9 on 2021-12-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='now_date',
            field=models.DateField(blank=True, null=True, verbose_name='今の日付'),
        ),
    ]
