# Generated by Django 3.2.9 on 2021-12-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follow_cd',
            new_name='subject_cd',
        ),
    ]
