# Generated by Django 3.2.9 on 2022-01-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='subject_koushi',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='講師名'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_koushi',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='講師名'),
        ),
    ]
