# Generated by Django 3.2.9 on 2021-12-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
    ]
