# Generated by Django 3.2.9 on 2022-01-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20220114_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_already',
            field=models.BooleanField(default=False),
        ),
    ]
