# Generated by Django 3.2.9 on 2022-01-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_project_is_already'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_already',
            field=models.BooleanField(default=False, verbose_name='提出済み'),
        ),
    ]
