# Generated by Django 3.2.9 on 2021-11-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='アイコン'),
        ),
    ]
